version: "3.3"

services:

  mongo:
    image: mongo:latest
    volumes:
      - top100-data:/data/db
      - top100-config:/data/configdb
    networks:
      - top100
    ports:
      - 27019:27017

  top100ui:
    image: sharkfoo/top100ui:latest
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/top100
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      restart_policy:
        condition: any
    networks:
      - top100
    ports:
      - 0.0.0.0:5000:80

networks:
  top100:

volumes:
  top100-data:
  top100-config:
