version: "3.1"

services:

  mongo:
    image: mongo:latest
    volumes:
      - top100-data:/data/db
      - top100-config:/data/configdb
    ports:
      - 27018:27017

  top100import:
    image: kpearson/top100import:latest
    build:
      context: Top100Import
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/top100
      ASPNETCORE_ENVIRONMENT: Development

  top100:
    image: kpearson/top100:latest
    build:
      context: Top100
      args:
        - port=5000
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/top100
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:5000


volumes:
  top100-data:
  top100-config:
